### ISSUE TITLE
Store and verify API token on client

### ISSUE THREAD

**Issue by jehrhardt** [cozystack/.github#10]
### Tasks

- [ ] Add API to fetch public key
- [ ] Verify API token signature in CLI
- [ ] Store API token securely on device

**Comment by jehrhardt** [comment]
This is no longer required due to the [MVP development](https://github.com/orgs/cozystack/discussions/15).
