### ISSUE TITLE
Add `cozyauth auth login` command with Supabase oAuth 2 flow

### ISSUE THREAD

**Issue by jehrhardt** [cozystack/.github#9]
### Tasks

- [x] Setup CLI project
- [x] Add `cozyauth auth login` command
- [ ] Add TUI with oAuth 2 URL
- [ ] Add login API
- [ ] Fetch access token from Supabase
- [ ] Store Supabase access token in Vault

**Comment by jehrhardt** [comment]
This is no longer required due to the [MVP development](https://github.com/orgs/cozystack/discussions/15).
